# Generated by Django 3.2.5 on 2021-07-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('pages', models.PositiveIntegerField()),
                ('cover', models.PositiveSmallIntegerField(choices=[(1, 'Hard'), (2, 'Soft')])),
                ('authors', models.ManyToManyField(to='api.Author')),
            ],
        ),
    ]
