# Generated by Django 3.2.5 on 2021-07-25 10:35

from django.db import migrations

def some_work(*args, **kwargs):
    print('hello', args, kwargs)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=some_work)
    ]
